[package]
name = "xi-correlation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
ordered-float = "2.8.0"
rand = "0.8.4"
textplots = "0.8.0"
